#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------
rm -f log*
rm -r constant/polyMesh
rm -r 0
rm -r processor*

#------------------------------------------------------------------------------
