#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

rm -f log*
rm -r constant/polyMesh
rm -r constant/extendedFeatureEdgeMesh
rm -r 0
rm -r fluentInterface
rm -r processor*
rm -r postProcessing

#------------------------------------------------------------------------------
