#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

touch bg.foam

blockMesh > log.blockMeshBackground

snappyHexMesh -overwrite > log.snappyHexMeshBackground 

topoSet -dict system/topoSetDictZ0 > log.topoSetZeroBackground 

for i in 1 2 3 4 5
do
    foamDictionary  system/refineMeshDictZ -entry set -set c${i}

    topoSet -dict system/topoSetDictZ> log.topoSetBackground${i}

    refineMesh -dict system/refineMeshDictZ -overwrite> log.refineBackground${i}
done

rm -f constant/polyMesh/cellLevel
rm -f constant/polyMesh/pointLevel
rm -f constant/polyMesh/level0Edge
rm -r 0

renumberMesh -constant -overwrite > log.renumberMeshBackground 

checkMesh > log.checkMeshBackground 

foamMeshToFluent > log.foamMeshToFluentBackground
#------------------------------------------------------------------------------
