#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------
rm -f log*
rm -r fluentInterface
rm -r constant/polyMesh
rm -r 0
rm -r processor*

touch bg.foam

blockMesh 
snappyHexMesh -overwrite 
topoSet -dict system/topoSetDictZ0 

for i in 1 2 3 4 5
do
    foamDictionary  system/refineMeshDictZ -entry set -set c${i}

    topoSet -dict system/topoSetDictZ

    refineMesh -dict system/refineMeshDictZ -overwrite
done

foamMeshToFluent
#------------------------------------------------------------------------------
