#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

bash ./Allmesh
mergeMeshes . ../ship -overwrite > log.mergeMesh
topoSet -dict system/topoSetDictzoneIDs > log.topoSetDictzoneIDs

cp -r 0.orig 0
setFields > log.setFields # assign zoneIDs and alpha.water

decomposePar -force > log.decomposePar 
mpirun -np 40 $(getApplication) -parallel > log.overInterDyFoam
mpirun -np 40 redistributePar -reconstruct -overwrite > log.redistributePar 

#------------------------------------------------------------------------------