#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

bash ./Allmesh

cp -r 0.orig 0

mergeMeshes . ../ship -overwrite > log.mergeMesh

topoSet -dict system/topoSetDictzoneIDs > log.topoSetDictzoneIDs

setFields > log.setFields # assign zoneIDs and alpha.water

decomposePar -force > log.decomposePar

mpirun -np 80 overInterDyMFoam -parallel > log.overInterDyMFoam

mpirun -np 80 redistributePar -reconstruct -parallel > log.redistributePar 

#------------------------------------------------------------------------------