#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

bash ./Allmesh

restore0Dir

runApplication mergeMeshes . ../ship -overwrite

runApplication -s zoneIDs topoSet -dict system/topoSetDict # create cellSets

runApplication setFields # assign zoneIDs and alpha.water

runApplication decomposePar -force
runParallel $(getApplication)
runParallel redistributePar -reconstruct -overwrite

#------------------------------------------------------------------------------
