#!/bin/sh
cd "${0%/*}" || exit                                
#------------------------------------------------------------------------------

rm -f log*
rm -r constant/polyMesh
rm -r constant/extendedFeatureEdgeMesh
rm -r 0
rm -r fluentInterface

touch DTCShip.foam

blockMesh > log.blockMesh

surfaceFeatureExtract > log.surfaceFeatureExtract

decomposePar > log.decomposePar1
mpirun -np 40 snappyHexMesh -parallel -dict system/snappyHexMeshDictCastellated -overwrite > log.snappyHexMeshCastellated

mpirun -np 40 redistributePar -reconstruct -parallel -constant -withZero > log.redistributePar1
ls -d processor* | xargs -i rm -rf ./{} $1

# z-dir refinement for free surface
topoSet -dict system/topoSetDict > log.topoSet
refineMesh -dict system/refineMeshDictZ -overwrite  > log.refineMesh
rm -f 0/cellLevel
rm -f 0/pointLevel
rm -f constant/polyMesh/pointLevel
rm -f constant/polyMesh/level0Edge
rm -f constant/polyMesh/cellLevel

decomposePar > log.decomposePar2
mpirun -np 40 snappyHexMesh -parallel -dict system/snappyHexMeshDictSnapLayers -overwrite > log.snappyHexMeshDictSnapLayers

mpirun -np 40 redistributePar -reconstruct -parallel -constant -withZero > log.redistributePar2
ls -d processor* | xargs -i rm -rf ./{} $1

renumberMesh -constant -overwrite > log.renumberMesh

foamMeshToFluent > log.foamMeshToFluent

#------------------------------------------------------------------------------